Vagrant.configure("2") do |config|
  config.vm.box = "micro-suse"                                         
  config.vm.provider :libvirt do |libv|                                                                                              
    libv.memory = 4096                                                                                                                
  end
  
end
