# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "alpine318"                                                                                                     
  config.vm.hostname = "geek"                                                                                                
  config.vm.network :private_network, ip: "192.168.60.11"                                                                          
  config.ssh.insert_key = false                                                                                                    
  config.vm.synced_folder ".", "/vagrant", disabled: false 
  
  config.vm.provider :virtualbox do |v|                                                                                              
    v.memory = 4096                                                                                                                
  end
  
  # Ansible provisioner.
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "playbook.yml"
  end
end