# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "alpine318"
  config.ssh.insert_key = false
  config.vm.network "forwarded_port", guest: 80, host: 8081
  config.vm.network "public_network"
  config.vm.synced_folder "../vagrant", "/vagrant_data"
  
  config.vm.provider "virtualbox" do |vb|
    vb.name = "alpine_web"
    vb.cpus = "2"
    vb.memory = "1024"
  end
  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
