---
- name: Lineinfile Examples
  hosts: all
  tasks:
  - name:
    lineinfile:
      path: ~/.bashrc
      regexp: '^HISTSIZE='
      line: HISTSIZE=5000
  - name:
    lineinfile:
      path: ~/.bashrc
      regexp: '^HISTFILESIZE='
      line: HISTFILESIZE=10000
