# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian12"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
    vb.memory = 4096
    vb.cpus = 2
  end

  config.vm.define "attacker" do |attacker|
    attacker.vm.hostname = "attacker.com"
    attacker.vm.network "public_network", bridge: "enp30s0"
  end

  config.vm.define "victim" do |victim|
    victim.vm.hostname = "victim.com"
    victim.vm.network "public_network", bridge: "enp30s0"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.limit = "all"
    ansible.playbook = "ignition.yaml"
    ansible.extra_vars = {
    ansible_user: "vagrant",
    ansible_ssh_private_key_file: "~/.vagrant.d/insecure_private_key"
    }
  end
end
